<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student
[
<!ELEMENT student (stud)>
<!ELEMENT stud (name,initial,age)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT initial (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!-- //<!ELEMENT fname "Hitesh">
* 0 or many
+ 1 or many
? optiona
-->
]>
<student>
<stud>
<name>&amp;&gt;Hitesh</name>
<initial>hey</initial>
<age>26</age>
</stud>
<stud>
<name >Hitesh </name>
<initial>hey</initial>
<age>26</age>
</stud>
</student>
